fix: Correct coverage check script

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -28,19 +28,19 @@ jobs:
                   echo "testé"
             - name: Check Jest coverage
               run: |
-                COVERAGE_THRESHOLD=80
-                ACTUAL_COVERAGE=$(sed -n 's/^Statements.*: \([0-9]*\.[0-9]*\)%.*/\1/p' coverage/lcov-report/index.html)
-                if [[ -n $ACTUAL_COVERAGE ]]; then
-                  if (( $(echo "$ACTUAL_COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
-                    echo "Coverage is below the threshold ($ACTUAL_COVERAGE%)"
-                    exit 1
+                  COVERAGE_THRESHOLD=80
+                  ACTUAL_COVERAGE=$(sed -n 's/^Statements.*: \([0-9]*\.[0-9]*\)%.*/\1/p' coverage/lcov-report/index.html)
+                  if [[ -n $ACTUAL_COVERAGE ]]; then
+                    if (( $(echo "$ACTUAL_COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
+                      echo "Coverage is below the threshold ($ACTUAL_COVERAGE%)"
+                      exit 1
+                    else
+                      echo "Coverage is above the threshold ($ACTUAL_COVERAGE%)"
+                    fi
                   else
-                    echo "Coverage is above the threshold ($ACTUAL_COVERAGE%)"
+                    echo "Error: Coverage percentage not found or invalid."
+                    exit 1
                   fi
-                else
-                  echo "Error: Coverage percentage not found or invalid."
-                  exit 1
-                fi
             - run: |
                   npm run build
                   echo "buildé"
